baseURL = 'https://example.org/'
languageCode = 'sv'
title = 'DragosLarm AB'
theme = 'dragos'

[module]
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"

[[menus.main]]
name = 'Hem'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Larm'
pageRef = '/produkter'
weight = 20

[[menus.main]]
name = 'Manualer'
pageRef = '/manualer'
weight = 30

[[menus.main]]
name = 'Nyheter'
pageRef = '/nyheter'
weight = 40
